# Generated by Django 5.1.15 on 2026-09-23 17:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('customer_type', models.CharField(blank=True, default='Shipper / Customer', max_length=50)),
                ('short_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('pan', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer (Consignor)',
                'verbose_name_plural': 'Customers (Consignors)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('transporter_type', models.CharField(blank=True, default='Transporter', max_length=50)),
                ('short_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pan', models.CharField(blank=True, db_index=True, help_text='PAN required for TDS reporting', max_length=20)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('bank_details', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transporter (Lorry Owner)',
                'verbose_name_plural': 'Transporters (Lorry Owners)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('default_capacity_tons', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='historicalownerpayment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Transporter Payment (Outward)', 'verbose_name_plural': 'historical Transporter Payments (Outward)'},
        ),
        migrations.AlterModelOptions(
            name='historicalreceipt',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Receipt (Inward Payment)', 'verbose_name_plural': 'historical Receipts (Inward Payments)'},
        ),
        migrations.AlterModelOptions(
            name='historicaltrip',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Trip (LR Register)', 'verbose_name_plural': 'historical Trips (LR Register)'},
        ),
        migrations.AlterModelOptions(
            name='ownerpayment',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Transporter Payment (Outward)', 'verbose_name_plural': 'Transporter Payments (Outward)'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Receipt (Inward Payment)', 'verbose_name_plural': 'Receipts (Inward Payments)'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-lr_no'], 'verbose_name': 'Trip (LR Register)', 'verbose_name_plural': 'Trips (LR Register)'},
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, default='City', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='pincode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capacity_tons',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fitness_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_details',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='permit_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalownerpayment',
            name='mode',
            field=models.CharField(choices=[('UPI', 'UPI'), ('PHONEPE', 'PhonePe'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('ADJUSTMENT', 'Adjustment'), ('OTC', 'OTC')], default='BANK_TRANSFER', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalreceipt',
            name='mode',
            field=models.CharField(choices=[('UPI', 'UPI'), ('PHONEPE', 'PhonePe'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('ADJUSTMENT', 'Adjustment'), ('OTC', 'OTC')], default='UPI', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalreceipt',
            name='reference',
            field=models.CharField(blank=True, help_text='UPI ref, cheque no, transaction id', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaltrip',
            name='advance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Advance due from customer', max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicaltrip',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('1500.00'), help_text='Commission deduction', max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicaltrip',
            name='destination',
            field=models.CharField(help_text='e.g. Noida or Etah + Kamah', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaltrip',
            name='financial_year',
            field=models.CharField(db_index=True, help_text='e.g. 2022-23, 2025-26', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicaltrip',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Freight / revenue amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicaltrip',
            name='holding',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Holding amount (days * rate or manual amount)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicaltrip',
            name='holding_days',
            field=models.PositiveIntegerField(default=0, help_text='Detention days'),
        ),
        migrations.AlterField(
            model_name='historicaltrip',
            name='holding_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Daily detention rate', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicaltrip',
            name='labour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Labour / hamali charge', max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicaltrip',
            name='lorry_advance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Advance paid to lorry at loading', max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicaltrip',
            name='lorry_balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Agreed balance due to lorry owner', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltrip',
            name='memo_no',
            field=models.PositiveIntegerField(blank=True, help_text='Memo number from book', null=True),
        ),
        migrations.AlterField(
            model_name='historicaltrip',
            name='memo_pending',
            field=models.BooleanField(db_index=True, default=False, help_text='True if memo is not yet issued'),
        ),
        migrations.AlterField(
            model_name='historicaltrip',
            name='origin',
            field=models.CharField(help_text='e.g. Silvassa or Silvassa + Vapi', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaltrip',
            name='tds',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='TDS withheld from lorry owner', max_digits=12),
        ),
        migrations.AlterField(
            model_name='ownerpayment',
            name='mode',
            field=models.CharField(choices=[('UPI', 'UPI'), ('PHONEPE', 'PhonePe'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('ADJUSTMENT', 'Adjustment'), ('OTC', 'OTC')], default='BANK_TRANSFER', max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='mode',
            field=models.CharField(choices=[('UPI', 'UPI'), ('PHONEPE', 'PhonePe'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('ADJUSTMENT', 'Adjustment'), ('OTC', 'OTC')], default='UPI', max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='reference',
            field=models.CharField(blank=True, help_text='UPI ref, cheque no, transaction id', max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='advance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Advance due from customer', max_digits=12),
        ),
        migrations.AlterField(
            model_name='trip',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('1500.00'), help_text='Commission deduction', max_digits=12),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(help_text='e.g. Noida or Etah + Kamah', max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='financial_year',
            field=models.CharField(db_index=True, help_text='e.g. 2022-23, 2025-26', max_length=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Freight / revenue amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='trip',
            name='holding',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Holding amount (days * rate or manual amount)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='trip',
            name='holding_days',
            field=models.PositiveIntegerField(default=0, help_text='Detention days'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='holding_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Daily detention rate', max_digits=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='labour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Labour / hamali charge', max_digits=12),
        ),
        migrations.AlterField(
            model_name='trip',
            name='lorry_advance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Advance paid to lorry at loading', max_digits=12),
        ),
        migrations.AlterField(
            model_name='trip',
            name='lorry_balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Agreed balance due to lorry owner', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='memo_no',
            field=models.PositiveIntegerField(blank=True, help_text='Memo number from book', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='memo_pending',
            field=models.BooleanField(db_index=True, default=False, help_text='True if memo is not yet issued'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='origin',
            field=models.CharField(help_text='e.g. Silvassa or Silvassa + Vapi', max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tds',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='TDS withheld from lorry owner', max_digits=12),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='reg_no',
            field=models.CharField(db_index=True, help_text='Registration no. e.g. GJ15AT-3912', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalreceipt',
            name='consignor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='register.customer'),
        ),
        migrations.AlterField(
            model_name='historicaltrip',
            name='consignor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='register.customer'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='consignor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='register.customer'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='consignor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='register.customer'),
        ),
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('standard_distance_km', models.PositiveIntegerField(blank=True, null=True)),
                ('standard_transit_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lanes_as_destination', to='register.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lanes_as_origin', to='register.location')),
            ],
            options={
                'verbose_name': 'Lane / Route',
                'verbose_name_plural': 'Lanes / Routes',
                'ordering': ['name'],
                'unique_together': {('origin', 'destination')},
            },
        ),
        migrations.AddField(
            model_name='historicaltrip',
            name='lane',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='register.lane'),
        ),
        migrations.AddField(
            model_name='trip',
            name='lane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='register.lane'),
        ),
        migrations.AlterField(
            model_name='historicalownerpayment',
            name='lorry_owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='register.transporter'),
        ),
        migrations.AlterField(
            model_name='historicaltrip',
            name='lorry_owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='register.transporter'),
        ),
        migrations.AlterField(
            model_name='ownerpayment',
            name='lorry_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='register.transporter'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='lorry_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='register.transporter'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='default_owner',
            field=models.ForeignKey(blank=True, help_text='Default/primary owner or transporter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='register.transporter'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='register.vehicletype'),
        ),
        migrations.DeleteModel(
            name='Consignor',
        ),
        migrations.DeleteModel(
            name='LorryOwner',
        ),
    ]
